### ISSUE TITLE
Inconsistency with creating and deleting developers

### ISSUE THREAD

**Issue by smitarani** [apigee/apigee-config-maven-plugin#92] opened 2020-07-07 12:36 UTC
We are seeing inconsistency when creating and deleting Org configurations on "developers". In our CICD, we are using "Apigee maven deploy/config plugin" to deploy and undeploy edge org configs.

Scenario 1: When we are creating a "developer" using "Apigee maven config plugin" with -Dapigee.config.option=update it should:
1. Create the developer if not found
2. Else update the developer if found as per plugin behavior
Issue: Our CI server makes a GET API call on any Organizational configs to see if it exists or not, GET call to edge had been pretty inconsistent. It shows, developer doesn't exists but in reality, the developer does exists. At this point, the Apigee maven config plugin will try to create the developer but it fails to create the developer with 409 error.

Scenario 2: Same as above, when we are deleting the developer, GET call to Apigee edge returns developer not found but actually it does exists. So we are not able to delete it through our CICD pipelines.

Note: Create and delete org configs activities are happening in one single pipeline but at the different stages. We have also tried adding some time interval for delaying the process but that didn't work. We also reached out to Apigee support but all the API management calls through curl are working all fine with our use cases. We are seeing this issue while using the maven plugin. 

I can further provide some evidence to display these issues if needed. 

Please let us know if is there anything known to this community. 

Thanks!

**Comment by ssvaidyanathan** [comment] 2020-07-07 15:25
@smitarani - Can you share more info please:

- Maven config plugin version you are using
- Sample of the calls that are failing. Can you share the cURL that worked
- error logs from your pipeline

**Comment by smitarani** [comment] 2020-07-08 13:23
Thanks for the reply. Please see all the details as you requested. 

**Maven config plugin version you are using**

                    <groupId>io.apigee.build-tools.enterprise4g</groupId>
                    <artifactId>apigee-edge-maven-plugin</artifactId>
                    <version>1.1.7</version>
          
                    <groupId>com.apigee.edge.config</groupId>
                    <artifactId>apigee-config-maven-plugin</artifactId>
                    <version>1.4.1</version>
     
**Sample of the calls that are failing. Can you share the cURL that worked**

**Create developer**

mvn apigee-config:developers \
    -Papigee \
    -Denv=dev \
    -Dorg=**** \
    -DvhostProtocol=https \
    -DvhostDomainName=**** \
    -DvhostDomainPort=443 \
    -DvhostEdgeName=**** \
    -Dapigee.config.dir=target/resources/edge \
    -Dapigee.config.options=update \
    -Dapigee.config.exportDir=target/test/integration \
    -Dapigee.api.port=8080 \
    -Dapigee.api.host=**** \
    -Dapigee.api.protocol=https \
    -Dtokenurl=***** \
    -Dauthtype=oauth \
    -Dbearer= ******  \
    -Drefresh=******

**Delete developer** 

mvn apigee-config:developers \
    -Papigee \
    -Denv=dev \
    -Dorg=**** \
    -DvhostProtocol=https \
    -DvhostDomainName=**** \
    -DvhostDomainPort=443 \
    -DvhostEdgeName=**** \
    -Dapigee.config.dir=target/resources/edge \
    -Dapigee.config.options=delete \
    -Dapigee.config.exportDir=target/test/integration \
    -Dapigee.api.port=8080 \
    -Dapigee.api.host=**** \
    -Dapigee.api.protocol=https \
    -Dtokenurl=***** \
    -Dauthtype=oauth \
    -Dbearer= ******  \
    -Drefresh=******

**Working cURLs**

**Curl for creating developer** 

curl -X POST --header "Content-Type: application/json" --header "Authorization: Bearer *********" -d "
  {
    \"email\": \"integration-testing-dev@xyz.com\",
    \"firstName\": \"integration\",
    \"lastName\": \"testing\",
    \"userName\": \"integration-testing-dev@xyz.com\",
    \"attributes\": [{
      \"name\": \"MINT_BILLING_TYPE\",
      \"value\": \"PREPAID\"
    }]
  }" "https://********/v1/organizations/{org}/developers"

**Curl to delete developer** 

curl -X DELETE --header "Authorization: Bearer ********" "https://********/v1/organizations/{org}/developers/integration-testing-dev@xyz.com"


**error logs from your pipeline**

**When we try to update the develop**

Request prepared for the server

**************************

GET https://********/v1/organizations/{org}/developers

accept: [application/json]

accept-encoding: [gzip]

authorization: [Bearer [Not shown in log]

[INFO] Creating Developer - integration-testing-dev@xyz.com

[INFO] Access Token valid

[INFO]

Request prepared for the server

**************************

POST https://*********/v1/organizations/{org}/developers

accept: [application/json]

accept-encoding: [gzip]

authorization: [Bearer [Not shown in log]

content-type: application/json

[Request body]

{"firstName":"integration","lastName":"testing","attributes":[{"name":"MINT_BILLING_TYPE","value":"PREPAID"}],"userName":"integration-testing-dev@xyz.com","email":"integration-testing-dev@xyz.com"}

[ERROR] Apigee call failed 409 Conflict

{

"code" : "developer.service.DeveloperAlreadyExists",

"message" : "Developer named integration-testing-dev@xyz.com already exists in organization {org}",

"contexts" : [ ]

}

**When we try to delete the existing developer** 

Request prepared for the server

**************************

GET https://******/v1/organizations/{org}/developers

accept: [application/json]

accept-encoding: [gzip]

authorization: [Bearer [Not shown in log]

[INFO] Developer "integration-testing-dev@xyz.com" does not exist. Skipping.

[INFO] ------------------------------------------------------------------------

[INFO] BUILD SUCCESS

Please let me know if you need any further details. 

Thanks.

**Comment by ssvaidyanathan** [comment] 2020-07-08 15:32
I tried the same and it works for me as expected. Added your sample payload to my developers.json and it works

**Comment by smitarani** [comment] 2020-07-08 16:38
When we do it for the first time, it always works but if you do this again then it will fail for the second time. 
Like what I am saying, execute the command to create a developer then run the command to delete the developer and repeat this process again probably 2-3 times to create and delete the developer. I am 100% positive you will get this error. I did so much testing on this.

**Comment by ssvaidyanathan** [comment] 2020-07-08 16:39
I did all that.. created, updated more than twice, deleted, re-created and then updated again

**Comment by smitarani** [comment] 2020-07-08 16:41
that's interesting. Can I replicate again and share the screenshots with you?

**Comment by smitarani** [comment] 2020-07-08 16:56
I just tried to replicate and still seeing the same issue. For the first 2 calls create and delete worked all good as expected. The third call for "create" worked good but when I executed the delete command it skipped the operation saying developer does not exist. Then for the fourth call "create" failed with 409 error "code" : "developer.service.DeveloperAlreadyExists",

**Comment by ssvaidyanathan** [comment] 2020-07-08 18:05
Are you using Apigee SaaS or Private Cloud?

**Comment by smitarani** [comment] 2020-07-08 19:33
Apigee SaaS

**Comment by ssvaidyanathan** [comment] 2020-07-08 19:44
Can you share your developers.json?

**Comment by smitarani** [comment] 2020-07-08 19:47
[
  {
    "email": "integration-testing@ferguson.com",
    "firstName": "integration",
    "lastName": "testing",
    "userName": "integration-testing@ferguson.com",
    "attributes": [{
      "name": "MINT_BILLING_TYPE",
      "value": "PREPAID"
    }]
  }
]

**Comment by ssvaidyanathan** [comment] 2020-07-08 22:25
I used your developers.json and tried your routine multiple times. It works for me.

Can you try the same sequence using Management API (using cURL?) and see if you are able to replicate it.

**Comment by smitarani** [comment] 2020-07-09 08:05
I used the same sequence with Management APIs and never get this issue. It's just happening with the Maven plugin. You did mention in your previous comment if we are making any changes to developer.json. Just wanted to provide some more detail here. We have 2 stages in our pipeline. 

**Actual Workflow of our pipeline**
Stage 1: It will deploy the developer from the developers.json file. Basically it will check on Apigee edge if developer exists then it will just update the existing developer or create the developer if not exists. 
In this developer email, we are tagging {env} variable so it can pick up the env name dynamically. It would look like this:
integration-testing-${env}@ferguson.com
So every time it will tag the env where we are deploying this developer. We never make any changes to the developers.json file. Env tagging is happening on the fly. Just FYI. 

Stage 2: We are simply deleting this developer. 

In both the stages as mentioned above, we are not changing anything to the developers.json file directly but we copy this file to the target folder on our CI server workspace and tag the env where we need to deploy this config. 
Another thing to notice which is really weird, it works fine for some calls but not for all the builds. 

We were assuming if it has something to do with time internal. Please suggest on this.

**Comment by ssvaidyanathan** [comment] 2020-07-09 16:00
It could be time interval as well as it involves Monetization as well. How quickly does your pipeline deletes and creates the developer? The plugin doesn't do anything but call the Management API and the response you see is also from the Management API. I suspect that pipeline is deleting / creating (or vice versa) sooner than its synced across your regions.

**Comment by smitarani** [comment] 2020-07-10 08:28
I would say within a 1-3 mins pipeline creates a developer and deletes it.

**Comment by ssvaidyanathan** [comment] 2020-07-10 14:24
Can you try these for me please: 
1) Write a script or use a client like POSTMAN that calls the create and delete multiple times. See what is the result. I do not think its a plugin issue

2) Remove the custom attributes from the developers.json and run the same test calling it multiple times. See if thats works ? Wondering if the Monetization attributes within the developer is taking a little longer so by the time you delete and create, its not completely done

Please try and provide an update

**Comment by smitarani** [comment] 2020-07-10 14:32
Sure, let me give it a try and update you. Thanks

**Comment by smitarani** [comment] 2020-07-15 07:46
1. Write a script or use a client like POSTMAN that calls the create and delete using Management API multiple times. Use the same payload you have in your developers.json. See what is the result. I do not think its a plugin issue
- I have tested the same sequence flow using POSTMAN with the same payload which has monetization attributes and did not get this error at all. (repeated this for around 20 times)
2. Remove the custom attributes from the developers.json and run the same test calling it multiple times. See if thats works ? Wondering if the Monetization attributes within the developer is taking a little longer so by the time you delete and create, its not completely done
- I did test this scenario removing custom attributes from the developers.json, it failed with the same error at the 5th request.

**Comment by ssvaidyanathan** [comment] 2020-07-15 20:31
Pls provide your email and timezone. Lets get on a meeting and see.. Am not able to reproduce this using the plugin.

**Comment by smitarani** [comment] 2020-07-16 19:58
Sure. Here is my email id Smitar@sidgs.com and I am in EST timezone. 
Can we please block something in our calendar for tomorrow? or any preferred time you would like to connect? Please advise. I will send the meeting invite accordingly. 
Thanks.

**Comment by ssvaidyanathan** [comment] 2020-07-17 23:55
On further analysis - look like the org has more than 1000 developers and in the initial GET call, the created developer is not in the list so the plugin assumes that the developer does not exist and proceeds with the creation. And during this process, the API fails.

**Comment by ssvaidyanathan** [comment] 2020-07-18 03:30
Released in v1.4.3
Please test and reopen the issue if you still find any issues

**Closed by ssvaidyanathan** 2020-07-18 03:30 UTC
