### ISSUE TITLE
Add option to manage users

### ISSUE THREAD

**Issue by paulwoelfel** [apigee/apigee-config-maven-plugin#97] opened 2020-09-08 07:11 UTC
Right now it is possible to manage user roles, but not users. It would be great to also include user management as another goal. 

The [APIs](https://apidocs.apigee.com/api-reference/content/user-api) do exist, so this should be possible

**Comment by ssvaidyanathan** [comment] 2020-09-08 18:00
@paulwoelfel - this was intentionally not added as its something that is not available in our SaaS product. Are you requesting this for a Private Cloud install ?

**Comment by paulwoelfel** [comment] 2020-09-14 11:53
Hi @ssvaidyanathan,

I've overlooked, that this API is only for private Cloud installation. 

We'd like to manage our users via Infrastructure as Code, so this would be a great feature. It's sad that an API first product hasn't got APIs for that.

**Comment by ssvaidyanathan** [comment] 2020-09-14 16:34
Hi @paulwoelfel 

Thats by design in our SaaS offering because we need the user to accept the terms and conditions. Let me know if we can close this issue.

**Closed** 2020-09-14 18:44 UTC
