### ISSUE TITLE
Developers App creates new Consumer Key every time maven update is run

### ISSUE THREAD

**Issue by bkarakashev** [apigee/apigee-config-maven-plugin#27] opened 2017-09-01 15:46 UTC
Every time I run mvn update for Developers App even if I haven't changed anything it's creating new Consumer Key in the app. Is it possible to disable that? as there is no need of new Consumer Key every time we run mvn update.
For example, if we add new attribute to the Developer App and run mvn update it will add new Consumer Key. I am not sure is doing this maybe my config is not correct. How can I disable that?

**Comment by ssvaidyanathan** [comment] 2017-09-01 15:58
@bkarakashev - this is a duplicate of https://github.com/apigee/apigee-config-maven-plugin/issues/17 

As you may know, the plugin is orchestrating the Mgmt API call. In this case, [Mgmt API](http://docs.apigee.com/management/apis/put/organizations/%7Borg_name%7D/developers/%7Bdeveloper_email_or_id%7D/apps/%7Bapp_name%7D) does that. We do not control it. If the Update Developer App request body contains a Product attribute, it updates the dev app and also creates a new credential. This is expected as you may have features where you need different creds for different Product setup. 

I can think of two work arounds:

1. For this scenario, where you just want to update custom attributes for an existing dev app, change the request body to exclude the products attribute (programmatically if possible) so that it does not create a new credential 
2. Instead of running update command, see if you can first run the delete and then run the create so that it always creates a new dev app with the latest body in your configuration

**Comment by bkarakashev** [comment] 2017-09-04 09:51
Will be nice if the plugin can support that. Not generating new Consumer Key every time.

**Comment by ssvaidyanathan** [comment] 2017-09-05 08:22
Sure.. Will mark https://github.com/apigee/apigee-config-maven-plugin/issues/17 as enhancement and tag this as a duplicate. Will see if we can include some option that will do this for you. But in the meanwhile you can follow the steps mentioned above

**Closed** 2017-11-04 04:26 UTC
Labels: duplicate
